name: deeprecsys
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip:
      - ipykernel
      - jupyter
      - keras==2.11.0
      - keras-preprocessing==1.1.2
      - matplotlib
      - matplotlib-inline
      - numpy<2.0.0
      - notebook
      - pandas
      - protobuf==3.19.6
      - tensorflow-recommenders==0.7.3
      - tensorflow-macos==2.11.0
      - tensorflow-metadata==1.9.0
      - tensorflow-datasets==4.8.2
      - google-cloud-storage==2.8.0
